create database webtracnghiem ;
use webtracnghiem;
create table user(
	id INT(10) NOT NULL auto_increment,
	name varchar(50),
    email varchar(50),
    phone INT(11),
	username varchar(50),
	password_hash varchar(60),
    total_score int(10),
    level varchar(50),
    primary key (id)
);

create table question(
	id INT(10) NOT NULL auto_increment,
	content varchar(300),
    difficult int(10),
    category varchar(50),
	primary key (id)
);

create table answer(
	id INT(10) NOT NULL auto_increment,
	id_question INT(10),
	content varchar(200),
	status boolean,
    primary key (id),
    FOREIGN KEY (id_question) REFERENCES question(id)
);

create table room(
	id INT(10) NOT NULL auto_increment,
    id_creator int(10),
    active boolean,
    primary key (id),
	FOREIGN KEY (id_creator) REFERENCES user(id)
);

create table room_question(
	id INT(10) NOT NULL auto_increment,
    id_room INT(10),
    id_question INT(10),
    primary key (id),
    foreign key (id_room) references room(id),
    foreign key (id_question) references question(id)
);

create table room_member(
	id int(10),
    id_room int(10),
    id_user int(10),
    score int(10),
    primary key (id),
    foreign key (id_room) references room(id),
    foreign key (id_user) references user(id)
);

INSERT INTO question (id, content, difficult, category) VALUES
(1, 'Sự khác nhau cơ bản giữa truyền thông multicast và truyền thông broadcast là gì?', 1, 'IT'),
(2, 'Giao thức nào sử dụng địa chỉ IP là 224.0.0.5 và 224.0.0.6 cho truyền thông multicast?', 1, 'IT'),
(3, 'Sử dụng Internet Group Management Protocol version 2 (IGMPv2), một nút mạng làm thế nào để thoát ra hoặc ngừng tham gia vào một nhóm multicast?', 1, 'IT'),
(4, 'Constructor là gì?', 1, 'IT'),
(5, 'Đâu là cách khai báo tạo ra chuỗi ký tự?', 1, 'IT'),
(6, 'Phương thức getInetAddress() trong lớp Socket được dùng để làm gì?', 1, 'IT'),
(7, 'Phương thức replaceFirst(char old, char new) được dùng để làm gì?', 1, 'IT'),
(8, 'Mô hình Client - Server thỏa mãn điều kiện nào?', 1, 'IT'),
(9, 'Chương trình được viết bằng ngôn ngữ Java có thể chạy trên bất kỳ nền nào bởi vì…', 1, 'IT'),
(10, 'Phương thức getPort() trong lớp URL có ý nghĩa gì ?', 1, 'IT'),
(11, 'Mô hình Client - Server thỏa mãn điều kiện nào?', 1, 'IT'),
(12, 'Chương trình được viết bằng ngôn ngữ Java có thể chạy trên bất kỳ nền nào bởi vì…', 1, 'IT'),
(13, 'Phương thức getPort() trong lớp URL có ý nghĩa gì?', 1, 'IT'),
(14, 'Phương thức getData() trong lớp DatagramPacket được sử dụng với mục đích gì?', 1, 'IT'),
(15, 'Lớp String thuộc package nào?', 1, 'IT'),
(16, 'Phương thức getPort() trong lớp DatagramPacket được sử dụng với mục đích gì?', 1, 'IT'),
(17, 'Điền vào phần ... cho phát biểu sau: "Mỗi gói dữ liệu chứa các thông tin: Dữ liệu, chiều dài gói, ...., và số cổng"', 1, 'IT'),
(18, 'Điền vào phần ... cho phát biểu sau: "Mỗi gói dữ liệu chứa các thông tin:..., chiều dài gói, địa chỉ IP, và số cổng"', 1, 'IT'),
(19, 'Điền vào phần …… cho phát biểu sau: "Mỗi gói dữ liệu chứa các thông tin: Dữ liệu, ……, địa chỉ IP, và số cổng"', 1, 'IT'),
(20, 'Điền vào phần ... cho phát biểu sau: "Mỗi gói dữ liệu chứa các thông tin: Dữ liệu, chiều dài gói, địa chỉ IP , và ...."', 1, 'IT'),
(21, 'Các định nghĩa phương thức sau đây định nghĩa nào sai:', 2, 'IT'),
(22, 'Trong cùng một máy có nhiều ứng dụng mạng cùng chạy, để phân biệt các ứng dụng với nhau thường dùng thông số nào sau đây?', 2, 'IT'),
(23, 'Điền phần còn thiếu cho cú pháp hàm sau DatagramPacket( …… buf[], int len) trong lớp DatagramPackage', 2, 'IT'),
(24, 'Mỗi gói dữ liệu trong lập trình mạng chứa thông tin gì?', 2, 'IT'),
(25, 'Phương thức writeBytes( String v) trong lớp DataOutputStream được sử dụng với mục đích gì?', 2, 'IT'),
(26, 'Phương thức getPort( ) trong lớp Socket được dùng để làm gì?', 2, 'IT'),
(27, 'Phương thức ServerSocket(int port, int count) trong lớp ServerSocket được sử dụng với mục đích gì?', 2, 'IT'),
(28, 'Lớp Soket trong lập trình mạng được sử dụng khi viết chương trình bên phía máy nào trong lập trình theo mô hình Client/Server:', 2, 'IT'),
(29, 'Phuương thức writeInt( int v)trong lớp DataOutputStream được sử dụng với mục đích gì?', 2, 'IT'),
(30, 'Điền phần còn thiếu cho cú pháp hàm sau: DatagramPacket( byte buf..., int len) trong lớp DatagramPackage', 2, 'IT'),
(31, 'Điền phần còn thiếu cho cú pháp hàm sau: DatagramPacket( byte buf[], ...len) trong lớp DatagramPackage', 2, 'IT'),
(32, 'Lớp nào cung cấp các phương tiện để người sử dụng có thể truy nhập được vào môi trường OSI và cung cấp các dịch vụ thông tin phân tán', 2, 'IT'),
(33, 'Tầng nào trong mô hình OSI làm việc với các tín hiệu điện?', 2, 'IT'),
(34, 'Để cấp phát động địa chỉ IP, ta có thể sử dụng dịch vụ có giao thức nào:', 2, 'IT'),
(35, 'Protocol là?', 2, 'IT'),
(36, 'Mô hình Client - Server là mô hình như thế nào?', 2, 'IT'),
(37, 'Java chạy trên hệ điều hành nào sau đây:', 2, 'IT'),
(38, 'Lệnh if CONDITION { Khối lệnh } có tác dụng gì?', 2, 'IT'),
(39, 'Kiểu dữ liệu byte có phạm vi trong khoảng nào?', 2, 'IT'),
(40, 'Lệnh str.charat(n) có tác dụng gì?', 2, 'IT'),
(41, 'Lệnh result = condition ? value1 : value2 có nghĩa gì?', 3, 'IT'),
(42, 'Để kiểm tra 2 chuỗi có bằng nhau hay không, sử dụng phương thức nào?', 3, 'IT'),
(43, 'Mục đích chính của các câu lệnh import là….', 3, 'IT'),
(44, 'Biên dịch có lỗi và đưa ra thông báo lỗi "Duplicate main() method declaration"', 3, 'IT'),
(45, 'Lớp là gì?', 3, 'IT'),
(46, 'Để khai báo lớp Xedap1 kế thừa lớp Xedap phải làm nhưthế nào?', 3, 'IT'),
(47, 'Cách đặt tên nào sau đây là không chính xác?', 3, 'IT'),
(48, 'Phương thức hasNext() trong lớp Scanner có tác dụng?', 3, 'IT'),
(49, 'Lệnh khai báo Scanner in = new Scanner(System.in); có tác dụng gì?', 3, 'IT'),
(50, 'Phương thức nextInt() trong lớp Scanner có tác dụng?', 3, 'IT'),
(51, 'Vị thế của nền kinh tế Mĩ sau chiến tranh thế giới thứ hai như thế nào?', 1, 'Sử'),
(52, 'Mĩ trở thành trung tâm kinh tế, tài chính duy nhất của thế giới vào khoảng thời gian nào?', 1, 'Sử'),
(53, 'Ý nào dưới đây không phải nguyên nhân thúc đẩy nền kinh tế Mĩ phát triển sau Chiến tranh thế giới thứ hai?', 1, 'Sử'),
(54, 'Nền kinh tế Mĩ mất dần ưu thế tuyệt đối về mọi mặt từ khoảng thời gian nào?', 1, 'Sử'),
(55, 'Ý nào dưới đây không phải nguyên nhân làm cho địa vị kinh tế Mĩ suy giảm?', 1, 'Sử'),
(56, 'Nước nào khởi đầu cuộc cách mạng khoa học – kĩ thuật hiện đại?', 1, 'Sử'),
(57, 'Thành tựu nổi bật trong chinh phục vũ trụ của Mĩ trong cuộc cách mạng khoa học kĩ thuật hiện đại là gì?', 1, 'Sử'),
(58, 'Sau Chiến tranh thế giới thứ hai, hai Đảng nào thay nhau nắm quyền ở Mĩ?', 1, 'Sử'),
(59, 'Chính sách đối ngoại mà các đời tổng thống Mĩ theo đuổi đều nhằm mục đích gì?', 1, 'Sử'),
(60, 'Ý nào dưới đây không phải mục đích của “Chiến lược toàn cầu” do Mĩ đề ra?', 1, 'Sử'),
(61, 'Sự kiện nào được coi à “Ngọn gió thần” đối với nền kinh tế Nhật Bản?', 1, 'Sử'),
(62, 'Cơ hội mới để nền kinh tế Nhật Bản đạt được sự tăng trưởng “thần kì” là gì?', 1, 'Sử'),
(63, 'Những năm 60 của thế kỉ XX, vị thế của nền kinh tế Nhật Bản như thế nào trong giới tư bản chủ nghĩa?', 1, 'Sử'),
(64, 'Nhật Bản trở thành một trong ba trung tâm kinh tế - tài chính của thế giới từ khi nào?', 1, 'Sử'),
(65, 'Ở Nhật Bản yếu tố nào được coi là vốn quý nhất, là nhân tố quyết định cho sự phát triển của nền kinh tế?', 1, 'Sử'),
(66, 'Nền kinh tế Nhật Bản lâm vào tình trạng suy thoái từ khi nào?', 1, 'Sử'),
(67, 'Nhật Bản đã làm gì để thúc đẩy sự phát triển của khoa học – kĩ thuật?', 1, 'Sử'),
(68, 'Trong thời gian 1955 – 1993, Đảng nào liên tục cầm quyền ở Nhật Bản?', 1, 'Sử'),
(69, 'Mục đích của việc Nhật Bản kí với Mĩ “Hiệp ước an ninh Mĩ – Nhật” là gì?', 1, 'Sử'),
(70, 'Từ những năm 90 của thế kỉ XX, mục tiêu lớn nhất mà Nhật Bản muốn hướng đến là gì?', 1, 'Sử'),
(71, 'Cơ cấu nông nghiệp nước ta đang thay đổi theo hướng:', 1, 'Địa'),
(72, 'Chiếm tỉ trọng cao nhất trong cơ cấu giá trị sản xuất ngành trồng trọt của nước ta:', 1, 'Địa'),
(73, 'Nền nông nghiệp nước ta thay đổi theo hướng:', 1, 'Địa'),
(74, 'Ở nước ta cây lúa được trồng chủ yếu ở:', 1, 'Địa'),
(75, 'Do trồng nhiều giống lúa mới nên:', 1, 'Địa'),
(76, 'Một trong những tác động của việc đẩy mạnh trồng cây công nghiệp:', 1, 'Địa'),
(77, 'Ở nước ta, chăn nuôi trâu chủ yếu ở:', 1, 'Địa'),
(78, 'Ở nước ta chăn nuôi chiếm tỉ trọng thấp trong nông nghiệp nguyên nhân chủ yếu là:', 1, 'Địa'),
(79, 'Vùng chăn nuôi lợn thường gắn chủ yếu với:', 1, 'Địa'),
(80, 'Tỉ trọng cây lương thực trong cơ cấu giá trị ngành trồng trọt đang giảm điều đó cho thấy:', 1, 'Địa'),
(81, 'Nhân tố tự nhiên ảnh hưởng lớn đến sự phát triển và sự phân bố công nghiệp là:', 1, 'Địa'),
(82, 'Dịch cúm H5N1 đã làm giảm đáng kể số lượng vật nuôi nào của nước ta?', 1, 'Địa'),
(83, 'Loại khoáng sản vừa là nguyên liệu vừa là nhiên liệu cho một số ngành khác là:', 1, 'Địa'),
(84, 'Các nguồn tài nguyên khoáng sản như apatit, pirit, photphorit,… là nguyên liệu cho ngành công nghiệp:', 1, 'Địa'),
(85, 'Ngành công nghiệp năng lượng phát triển mạnh nhất ở Quảng Ninh là:', 1, 'Địa'),
(86, 'Các nguồn tài nguyên khoáng sản như than, dầu, khí là nguyên liệu cho ngành công nghiệp:', 1, 'Địa'),
(87, 'Các nguồn tài nguyên khoáng sản như sắt, mangan, crom, chì, kẽm,… là nguyên liệu cho ngành công nghiệp:', 1, 'Địa'),
(88, 'Các nhân tố có vai trò quyết định đến sự phát triển và phân bố công nghiệp của nước ta là:', 1, 'Địa'),
(89, 'Nguồn lao động dồi dào, thị trường rộng lớn là cơ sở để phát triển mạnh ngành:', 1, 'Địa'),
(90, 'Nhân tố nào sau đây không phải là nhân tố kinh tế - xã hội ảnh hưởng đến sự phát triển công nghiệp :', 1, 'Địa'),
(91, 'Phong trào giải phóng dân tộc ở châu Phi diễn ra sớm nhất ở khu vực nào?', 2, 'Sử'),
(92, 'Sau chiến tranh thế giới thứ hai, phong trào giải phóng dân tộc châu Phi bùng nổ sớm nhất ở quốc gia nào?', 2, 'Sử'),
(93, 'Sự kiện nào là mốc mở đầu cho phong trào giải phóng dân tộc ở châu Phi?', 2, 'Sử'),
(94, 'Phong trào đấu tranh giành độc lập của nhân dân Ănggôla, Môdămbích nhằm đánh đổ ách thống trị của', 2, 'Sử'),
(95, 'Năm 1960, ở châu Phi đã diễn ra sự kiện lịch sử gì?', 2, 'Sử'),
(96, 'Năm 1960 đã đi vào lịch sử với tên gọi là “Năm châu Phi” bởi vì', 2, 'Sử'),
(97, 'Sự kiện nào là mốc đánh dấu sự sụp đổ về cơ bản của chủ nghĩa thực dân cũ ở châu Phi?', 2, 'Sử'),
(98, 'Sự kiện đánh dấu chủ nghĩa thực dân cũ ở châu Phi cùng hệ thống thuộc địa của nó cơ bản bị tan rã là', 2, 'Sử'),
(99, 'Năm 1975 có ý nghĩa đặc biệt với châu Phi vì', 2, 'Sử'),
(100, 'Ai là Tổng thống người da đen đầu tiên của Cộng hòa Nam Phi?', 2, 'Sử'),
(101, 'Nenxơn Manđêla trở thành tổng thống Nam Phi (1994) đánh dấu sự kiện lịch sử gì?', 2, 'Sử'),
(102, 'Năm 1993, chế độ phân biệt chủng tộc (Apacthai) sụp đổ ở Nam Phi đã chứng tỏ điều gì?', 2, 'Sử'),
(103, 'Nenxơn Manđêla trở thành tổng thống Nam Phi đánh dấu sự kiện lịch sử gì?', 2, 'Sử'),
(104, 'Đối tượng đấu tranh chủ yếu của phong trào giải phóng dân tộc ở châu Phi sau Chiến tranh thế giới thứ hai là', 2, 'Sử'),
(105, 'Hình thức đấu tranh chủ yếu của phong trào giải phóng dân tộc ở châu Phi sau chiến tranh thế giới 2 là gì?', 2, 'Sử'),
(106, 'Sự kiện gắn với tên tuổi của Nen-xơn Man-đê-la là', 2, 'Sử'),
(107, 'Văn bản pháp lý nào ở Nam Phi đã chính thức xóa bỏ chế độ phân biệt chủng tộc?', 2, 'Sử'),
(108, 'Tháng 11 -1993, Hiến pháp mới của Cộng hòa Nam Phi được thông qua đã', 2, 'Sử'),
(109, 'Đâu không phải là điều kiện khách quan thuận lợi dẫn đến bùng nổ phong trào giải phóng dân tộc ở châu Phi sau Chiến tranh thế giới thứ hai (1939 - 1945)?', 2, 'Sử'),
(110, 'Cuộc đấu tranh chống chế độ phân biệt chủng tộc ở Nam Phi được xếp vào cuộc đấu tranh giải phóng dân tộc vì', 2, 'Sử'),
(111, 'Dạng địa hình chiếm diện tích lớn nhất trên lãnh thổ nước ta là:', 2, 'Địa'),
(112, 'Địa hình nhiệt đới ẩm gió mùa của nước ta được biểu hiện rõ rệt ở:', 2, 'Địa'),
(113, 'Sự xâm thực mạnh mẽ tại miền đồi núi và bồi lắng phù sa tại các vùng trũng là biểu hiện đặc điểm nào của địa hình nước ta?', 2, 'Địa'),
(114, 'Địa hình núi nước ta được chia thành bốn vùng là:', 2, 'Địa'),
(115, 'Ranh giới tự nhiên của vùng núi Trường Sơn Bắc và Trường Sơn Nam là:', 2, 'Địa'),
(116, 'Nét nổi bật của địa hình vùng núi Tây Bắc là:', 2, 'Địa'),
(117, 'Căn cứ vào Atlat Địa lí Việt Nam trang 13, hãy cho biết Đèo Ngang nằm giữa hai tỉnh nào:', 2, 'Địa'),
(118, 'Đặc điểm chung của vùng đồi núi Trường Sơn Bắc là:', 2, 'Địa'),
(119, 'Nước ta nằm ở vị trí:', 2, 'Địa'),
(120, 'Đặc điểm chung của vùng đồi núi Trường Sơn Nam là:', 2, 'Địa'),
(121, 'Đây không phải là đặc điểm chung của vùng núi Đông Bắc:', 2, 'Địa'),
(122, 'Độ cao núi của Trường Sơn Bắc so với Trường Sơn Nam:', 2, 'Địa'),
(123, 'Đặc điểm nào sau đây không phải của dải đồng bằng ven biển miền Trung?', 2, 'Địa'),
(124, 'Đặc điểm không phải của dải đồng bằng sông Hồng là:', 2, 'Địa'),
(125, 'Căn cứ vào Atlat Địa lí Việt Nam trang  6 -7, hãy cho biết đồng bằng Nghệ An được hình thành do phù sa của sông nào bồi đắp?', 2, 'Địa'),
(126, 'Điểm giống nhau chủ yếu của địa hình vùng đồi núi Tây Bắc và Đông Bắc là:', 2, 'Địa'),
(127, 'Địa hình núi nước ta gồm những hướng chính là:', 2, 'Địa'),
(128, 'Điểm khác nhau chủ yếu của Đồng bằng sông Hồng so với Đồng bằng sông Cửu Long là ở đồng bằng này có:', 2, 'Địa'),
(129, 'Điểm khác nhau của Đồng bằng sông Cửu Long so với Đồng bằng sông Hồng là:', 2, 'Địa'),
(130, 'Điểm giống nhau chủ yếu nhất giữa địa hình bán bình nguyên và đồi là:', 2, 'Địa'),
(131, 'Hội nghị Ianta đã quyết định nhiều vấn đề quan trọng, ngoại trừ', 3, 'Sử'),
(132, 'Chín tháng là thời gian nhân dân Liên Xô', 3, 'Sử'),
(133, 'Điểm giống nhau giữa Nhật Bản và bốn "con rồng" kinh tế của châu Á là', 3, 'Sử'),
(134, 'ý nào dưới đây phản ánh mối quan hệ đối ngoại giữa Trung Quốc và Việt Nam diễn biến theo chiều hướng xấu?', 3, 'Sử'),
(135, 'Hãy sắp xếp các dữ kiện sau theo trình tự thời gian:1. Việt Nam và Lào tuyên bố độc laapk; 2. Nước Cộng hòa Indonexia thống nhất ra đời; 3. Việt Nam hoàn thành thống nhất đất nước về mặt nhà nước; 4. Philippin và Miến Điện(Mianma) được công nhận độc lập', 3, 'Sử'),
(136, 'Hiệp ước Bali (2 – 1976) đã xác định nhiều nguyên tắc hoạt động cơ bản trong quan hệ giữa các nước ASEAN, ngoại trừ nguyên tắc nào?', 3, 'Sử'),
(137, 'Ý nào dưới đây không phản ánh sự phát triển vượt bậc về kinh tế, khoa học – kĩ thuật của Mĩ những năm đầu sau chiến tranh thế giới thứ hai?', 3, 'Sử'),
(138, 'thành tựu lớn nhất mà các nước tây Âu đạt được trong những năm 50 – 70 của thế kỉ XX là', 3, 'Sử'),
(139, 'Sự kiện có ảnh hưởng lớn nhất đến tâm lí của người dân nước Mĩ trong mấy chục năm cuối thế kỉ XX là gì?', 3, 'Sử'),
(140, 'Sau chiến tranh thế giới thứ hai, quan hệ giữa Mĩ và Liên Xô thay đổi như thế nào?', 3, 'Sử'),
(141, 'Đặc điểm lớn nhất của công cuộc cách mạng khoa học – công nghệ là', 3, 'Sử'),
(142, 'trong xu thế hòa bình ổn định, hợp tác và phát triển, Việt Nam có được những thời cơ và thuận lợi là gì?', 3, 'Sử'),
(143, 'Sự kiện nào đánh dấu bước ngoặt trong cuộc đời hoạt động của Nguyễn Ái Quốc ?', 3, 'Sử'),
(144, 'Trong giai đoạn 1919 – 1925, công lao lớn nhất của Nguyễn Ái Quốc đối với cách mạng Việt Nam là', 3, 'Sử'),
(145, 'Vì sao Nguyễn Ái Quốc bỏ phiếu tán thành Quốc tế thứ ba?', 3, 'Sử'),
(146, 'Tổ chức cách mạng nào được coi là tiền thân của Đảng Cộng sản Việt Nam', 3, 'Sử'),
(147, 'Đầu năm 1929, Chi bộ Cộng sản đầu tiên được thành lập tại số nhà 5D phó Hàm Long (Hà Nội) là do', 3, 'Sử'),
(148, 'Văn kiện được coi là Cương lĩnh Chính trị đầu tiên của Đảng Cộng sản Việt Nam là', 3, 'Sử'),
(149, 'Ý nào không phản ánh đúng đóng góp của Nguyễn Ái Quốc trong Hội nghị hợp nhất các tổ chức cộng sản ở Việt Nam đầu năm 1930?', 3, 'Sử'),
(150, 'Văn kiện nào của Đảng xác định động lực cách mạng là công nhân và nông dân?', 3, 'Sử'),
(151, 'Nước ta tiếp giáp với Biển Đông, nên có', 3, 'Địa'),
(152, 'Biển Đông nằm trong vùng:', 3, 'Địa'),
(153, 'Vùng ven biển nước ta không có hệ sinh thái nào sau đây?', 3, 'Địa'),
(154, 'Loại thiên tai ít xảy ra ở vùng biển nước ta là:', 3, 'Địa'),
(155, 'Ý nào sau đây không phải là ảnh hưởng của biển Đông đến khí hậu của nước ta?', 3, 'Địa'),
(156, 'Biển Đông ảnh hưởng đến tính chất nào sau đây của khí hậu?', 3, 'Địa'),
(157, 'Khó khăn lớn nhất của nước ta do gần Biển Đông là:', 3, 'Địa'),
(158, 'Ở nước ta mùa hè bớt nóng bức là do:', 3, 'Địa'),
(159, 'Ở nước ta thời tiết mùa đông bớt lạnh khô, mùa hè bớt nóng bức là nhờ:', 3, 'Địa'),
(160, 'Nhờ có biển Đông nên khí hậu nước ta mang nhiều đặc tính của:', 3, 'Địa'),
(161, 'Đặc điểm sinh vật nhiệt đới của vùng biển Đông là:', 3, 'Địa'),
(162, 'Điểm nào sau đây không đúng khi nói về ảnh hưởng của Biển Đông đối với khí hậu nước ta:', 3, 'Địa'),
(163, 'Loại khoáng sản có giá trị kinh tế cao đang khai thác ở Biển Đông là:', 3, 'Địa'),
(164, 'Nhận định nào sau đây không đúng khi nói về ảnh hưởng của Biển Đông đến thiên nhiên nước ta?', 3, 'Địa'),
(165, 'Ở vùng ven biển, dạng địa hình nào thuận lợi nhất để xây dựng cảng biển?', 3, 'Địa'),
(166, 'Biển Đông là cầu nối giữa hai đại dương:', 3, 'Địa'),
(167, 'Tính chất nhiệt đới ẩm gió mùa của biển Đông không thể hiện ở:', 3, 'Địa'),
(168, 'Rừng ngập mặn ven biển ở nước ta phát triển mạnh nhất ở:', 3, 'Địa'),
(169, 'Biển Đông thường gây ra hậu quả nặng nề nhất cho các đồng bằng ven biển nước ta là thiên tai:', 3, 'Địa'),
(170, 'Tài nguyên quý giá ven các đảo nhất là 2 quần đảo Hoàng Sa và Trường Sa là:', 3, 'Địa');





INSERT INTO answer (id, id_question, content, status) VALUES 
(1, 1,'Multicast là gửi cho nhiều mạng được định nghĩa với multicast.', true),
(2, 1,'Multicast và broadcast về cơ bản là giống nhau.', false),
(3, 1,'Broadcast là gửi cho mọi nút mạng có đăng ký nhóm và/hoặc mạngcon.', false),
(4, 1,'Không phải các ý trên.', false),
(5, 2,'PIM.', false),
(6, 2,'OSPF.', true),
(7, 2,'EIGRP.', false),
(8, 2,'Không phải các ý trên', false),
(9, 3,'Nó phải tự thoát ra vì không có câu lệnh để thoát ra nhóm.', false),
(10, 3,'Cả nút và router phải được cấu hình với quyền admin để không tham gia vào một nhóm multicast cụ thể.', false),
(11, 3,'Nút không kiểm soát được việc tham gia nhóm multicast; router hoàn toàn quản lý nhóm multicast.', false),
(12, 3,'Nút phải đưa ra một câu lệnh nghỉ cụ thể.', true),
(13, 4,'Các hàm có tên trùng với tên lớp và không có tham số.', false),
(14, 4,'Các hàm có tên trùng với tên lớp và không có kiểu dữ liệu của hàm.', true),
(15, 4,'Hàm có tên trùng với tên lớp, kiểu dữ liệu của hàm là void', false),
(16, 4,'Hàm có tên trùng tên lớp và có dấu ngã ~ trước tên hàm.', false),
(17, 5,'String s = new String("Test")', false),
(18, 5,'String s;', false),
(19, 5,'Cả hai phương án đều đúng', true),
(20, 5,'Cả hai phương án đều sai', false),
(21, 6,'Lấy về số cổng được kết nối đến máy chủ', false),
(22, 6,'Lấy về luồng xuất để máy khách có thể gửi dữ liệu đến máy chủ', false),
(23, 6,'Lấy về luồng nhập để máy khách có thể đọc dữ liệu gửi trả về từ phía máy chủ', false),
(24, 6,'Lấy địa chỉ của máy chủ được kết nối đến dưới dạng kiểu InetAddress', true),
(25, 7,'Thay thế tất cả ký tự new bằng ký tự old trong một chuỗi nào đó', false),
(26, 7,'Thay thế tất cả các ký tự old bằng ký tự new trong một chuỗi nào đó', true),
(27, 7,'Thay thế ký tự old đầu tiên bằng ký tự new trong một chuỗi nào đó', false),
(28, 7,'Thay thế ký tự old cuối cùng bằng ký tự new trong một chuỗi nào đó', false),
(29, 8,'Một Client chỉ phục vụ yêu cầu của một Server', false),
(30, 8,'Một Server phục vụ yêu cầu của nhiều Client', true),
(31, 8,'Một Server chỉ phục vụ yêu cầu của một Client', false),
(32, 8,'Một Client phục vụ yêu cầu của nhiều Server', false),
(33, 9,'Máy ảo JVM được nhiều nền tảng hỗ trợ', true),
(34, 9,'Trình biên dịch được xác định bởi trình biên dịch của C++', false),
(35, 9,'Lập trình Java đ¬ợc kế thừa từ C++', false),
(36, 9,'Hàm API thực hiện các thao tác', false),
(37, 10,'Trả về tên của file trong một chuỗi địa chỉ URL', false),
(38, 10,'Trả về tên của máy chủ trong một chuỗi địa chỉ URL', false),
(39, 10,'Trả về số hiệu cổng sử dụng trong một chuỗi đĩa chỉ URL', true),
(40, 10,'Trả về tên của giao thức trong một chuỗi địa chỉ URL', false),
(41, 11,'Một Client phục vụ yêu cầu của nhiều Server', false),
(42, 11,'Một Server phục vụ yêu cầu của nhiều Client', true),
(43, 11,'Một Server chỉ phục vụ yêu cầu của một Client', false),
(44, 11,'Một Client chỉ phục vụ yêu cầu của một Server', false),
(45, 12,'Hàm API thực hiện các thao tác', false),
(46, 12,'Trình biên dịch được xác định bởi trình biên dịch của C++', false),
(47, 12,'Lập trình Java được kế thừa từ C++', false),
(48, 12,'Máy ảo JVM được nhiều nền tảng hỗ trợ', true),
(49, 13,'Trả về số hiệu cổng sử dụng trong một chuỗi đĩa chỉ URL', true),
(50, 13,'Trả về tên của giao thức trong một chuỗi địa chỉ URL', false),
(51, 13,'Trả về tên của máy chủ trong một chuỗi địa chỉ URL', false),
(52, 13,'Trả về tên của file trong một chuỗi địa chỉ URL', false),
(53, 14,'Trả về nội dụng dữ liệu thật sự chứa trong gói dữ liệu', true),
(54, 14,'Trả về địa chỉ chứa trong gói dữ liệu', false),
(55, 14,'Trả về kích thước của gói chứa trong gói dữ liệu', false),
(56, 14,'Trả về số hiệu cổng chứa trong gói dữ liệu', false),
(57, 15,'java.string', false),
(58, 15,'javax.util', false),
(59, 15,'java.util', false),
(60, 15,'java.lang', true),
(61, 16,'Trả về số hiệu cổng chứa trong gói dữ liệu', true),
(62, 16,'Trả về nội dụng dữ liệu thật sự chứa trong gói dữ liệu', false),
(63, 16,'Trả về địa chỉ chứa trong gói dữ liệu', false),
(64, 16,'Trả về kích thước của gói chứa trong gói dữ liệu', false),
(65, 17,'Số cổng', false),
(66, 17,'Chiều dài gói', false),
(67, 17,'Địa chỉ IP', true),
(68, 17,'Dữ liệu', false),
(69, 18,'Chiều dài gói', false),
(70, 18,'Địa chỉ IP', false),
(71, 18,'Dữ liệu', true),
(72, 18,'Số cổng', false),
(73, 19,'Địa chỉ IP', false),
(74, 19,'Dữ liệu', false),
(75, 19,'Chiều dài gói', true),
(76, 19,'Số cổng', false),
(77, 20,'Địa chỉ IP', false),
(78, 20,'Chiều dài gói', false),
(79, 20,'Dữ liệu', false),
(80, 20,'Số cổng', true),
(81, 21,'private float MyMethd(float z, int i){z=10;return z;}', false),
(82, 21,'static void My(float x){x=5;return x}', false),
(83, 21,'protected float MyMethd(float r, String s){r=10;return r;}', false),
(84, 21,'final float MyMethd(float y){}', true),
(85, 22,'Port D.', true),
(86, 22,'Địa chỉ IP', false),
(87, 22,'Tên miền', false),
(88, 22,'Tất cả đều sai', false),
(89, 23,'int', false),
(90, 23,'String', false),
(91, 23,'float', false),
(92, 23,'byte', true),
(93, 24,'Dữ liệu (data) và chiều dài gói (length)', false),
(94, 24,'Địa chỉ IP (address) và số cổng (port)', false),
(95, 24,'Cả hai phương án trên đều đúng', true),
(96, 24,'Cả hai phương án trên đều sai', false),
(97, 25,'Gửi một ký tự v tới nguồn xuất bất kỳ', false),
(98, 25,'Gửi một chuỗi ký tự v tới nguồn xuất bất kỳ', true),
(99, 25,'Gửi một số thực v tới nguồn xuất bất kỳ', false),
(100, 25,'Gửi một số nguyên v tới nguồn xuất bất kỳ', false),
(101, 26,'Lấy địa chỉ của máy chủ được kết nối đến dưới dạng kiểu InetAddress', false),
(102, 26,'Lấy về luồng nhập để máy khách có thể đọc dữ liệu gửi trả về từ phía máy chủ', false),
(103, 26,'Lấy về số cổng được kết nối đến máy chủ', true),
(104, 26,'Lấy về luồng xuất để máy khách có thể gửi dữ liệu đến máy chủ', false),
(105, 27,'Mở kết nối từ máy khách đến máy chủ', false),
(106, 27,'Mở kết nối từ máy khách đến máy chủ và mở kết nối từ phía máy chủ đến máy khách', false),
(107, 27,'Mở kết nối từ phía máy chủ chờ máy khách kết nối đến thông qua cổng port, cho phép số máy kết nối cùng lúc là count', true),
(108, 27,'Mở kết nối từ phía máy chủ chờ máy khách kết nối đến thông qua số hiệu cổng port', false),
(109, 28,'Máy chủ và máy khách', true),
(110, 28,'Không phải máy chủ và máy khách', false),
(111, 28,'Máy khách', false),
(112, 28,'Máy chủ', false),
(113, 29,'Gửi một chuỗi ký tự v tới nguồn xuất bất kỳ', false),
(114, 29,'Gửi một ký tự v tới nguồn xuất bất kỳ', false),
(115, 29,'Gửi một số thực v tới nguồn xuất bất kỳ', false),
(116, 29,'Gửi một số nguyên v tới nguồn xuất bất kỳ', true),
(117, 30,'[ ]', true),
(118, 30,'" "', false),
(119, 30,'{ }', false),
(120, 30,'()', false),
(121, 31,'String', false),
(122, 31,'int[]', false),
(123, 31,'int', true),
(124, 31,'Float', false),
(125, 32,'Presentation', false),
(126, 32,'Transport', false),
(127, 32,'Session', false),
(128, 32,'Application', true),
(129, 33,'Data Link', false),
(130, 33,'Physical', true),
(131, 33,'Network', false),
(132, 33,'Transport', false),
(133, 34,'Dùng giao thức FTP', false),
(134, 34,'Dùng giao thức HTTP', false),
(135, 34,'Dùng giao thức DHCP', true),
(136, 34,'Dùng giao thức DNS', false),
(137, 35,'Một trong những thành phần không thể thiếu trong hệ thống mạng', false),
(138, 35,'Là các qui tắc để cho phép các máy tính có thể giao tiếp được với nhau', false),
(139, 35,'A và B đúng', true),
(140, 35,'A và B sai', false),
(141, 36,'Là mô hình nhiều máy khách giao tiếp với nhau theo 1 hoặc nhiều dịch vụ', false),
(142, 36,'Là mô hình nhiều máy tớ giao tiếp với nhau theo 1 hoặc nhiều dịch vụ', false),
(143, 36,'Là mô hình nhiều máy con giao tiếp với nhau theo 1 hoặc nhiều dịch vụ', false),
(144, 36,'Là mô hình mạng trên đó có các máy chủ và máy tớ giao tiếp với nhau theo 1 hoặc nhiều dịch vụ', true),
(145, 37,'Sun Solaris OS', false),
(146, 37,'Microsoft Windows', false),
(147, 37,'Linux', false),
(148, 37,'Tất cả các đáp án đều đúng.', true),
(149, 38,'Nếu CONDITION đúng thì thực hiện Khối lệnh, nếu sai thì bỏ qua', true),
(150, 38,'Nếu CONDITION sai thì thực hiện Khối lệnh, nếu đúng thì bỏ qua', false),
(151, 38,'Không có đáp án đúng', false),
(152, 38,'Tất cả đều sai.', false),
(153, 39,'(-32,768) đến 32,767', false),
(154, 39,'0 đến 65535', false),
(155, 39,'(-256) đến 255', false),
(156, 39,'(-128) đến 127 +', true),
(157, 40,'Lấy ký tự có số chỉ mục n trong chuỗi k', true),
(158, 40,'Lấy ký tự bất kỳ trong chuỗi str', false),
(159, 40,'Lấy độ dài chuỗi str', false),
(160, 40,'Không có lệnh này', false),
(161, 41,'Nếu condition là true thì result = value2, nếu condition là false thì result = value1', false),
(162, 41,'Nếu condition là true thì result = value1, nếu condition là false thì result = value2', true),
(163, 41,'Không có lệnh này', false),
(164, 41,'Nếu condition là true thì result sẽ đảo giá trị của value1 và value2', false),
(165, 42,'string1 = string2', false),
(166, 42,'string1== string2', false),
(167, 42,'string1.equal(string2)', false),
(168, 42,'string1.equals(string2)', true),
(169, 43,'Để tham chiếu tới các lớp mà không cần tiền tố', true),
(170, 43,'Để tránh thực hiện lời gọi tới các phương thức', false),
(171, 43,'Để gọi tới các ảnh mà bạn muốn sử dụng', false),
(172, 43,'Để tránh khỏi phải khai báo biến', false),
(173, 44,'Biên dịch thành công và đưa màn hình kết quả "In first main()" khi chạy với đối số của a', true),
(174, 44,'Biên dịch thành công và đưa ra màn hình kết quả "a" khi chạy với đối số của a', false),
(175, 44,'Biên dịch thành công nhưng sẽ đưa ra lỗi xảy ra ngoại lệ khi chạy', false),
(176, 45,'Là đối tượng được khai báo để hoạt động trong chương trình.', false),
(177, 45,'Là bản thiết kế từ đó tạo ra các đối tượng', true),
(178, 45,'Là một chức năng trong java dùng để chứa đối tượng.', false),
(179, 45,'Tất cả đều sai.', false),
(180, 46,'class Xedap1 extends Xedap {}', true),
(181, 46,'public classs Xedap1 extend Xedap {}', false),
(182, 46,'class Xedap1 extend Xedap {}', false),
(183, 46,'Tất cả đều sai', false),
(184, 47,'_final', false),
(185, 47,'dem', false),
(186, 47,'final', true),
(187, 47,'$final', false),
(188, 48,'Kiểm tra xem từ đó đã có trong dữ liệu vào chưa', true),
(189, 48,'Di chuyển đến từ tiếp theo', false),
(190, 48,'Cả A, B đều đúng', false),
(191, 48,'Cả A, B đều sai', false),
(192, 49,'Cho phép ta đọc', false),
(193, 49,'Cho phép ta nhập vào 1 ký tự', false),
(194, 49,'Cho phép ta nhập vào 1 ký tự hay một chuỗi nào đó vào từ bàn phím', true),
(195, 49,'Cả A,B, C đều đúng', false),
(196, 50,'Đọc 1 giá trị số nguyên từ bàn phím', true),
(197, 50,'Đọc 1 chuỗi ký tự từ bàn phìm, kể cả dấu cách', false),
(198, 50,'Đọc 1 giá trị số thực từ bàn phím', false),
(199, 50,'Đọc 1 chuỗi ký tự từ bàn phím, không kể dấu cách', false),
(200, 44,'Biên dịch không thành công', false),
(201, 51,'Vươn lên đứng đầu trong giới tư bản chủ nghĩa.', true),
(202, 51,'Đứng thứ hai trong giới tư bản chủ nghĩa.', false),
(203, 51,'Đứng thứ ba trong giới tư bản chủ nghĩa.', false),
(204, 51,'Đứng thứ tư trong giới tư bản chủ nghĩa.', false),
(205, 52,'Từ năm 1945 đến 1975.', false),
(206, 52,'Từ năm 1950 đến 1980.', false),
(207, 52,'Từ năm 1918 đến 1945.', false),
(208, 52,'Từ năm 1945 đến 1950.', true),
(209, 53,'Mĩ giàu lên nhờ buôn bán vũ khí cho các nước tham chiến.', false),
(210, 53,'Tài nguyên thiên nhiên phong phú.', false),
(211, 53,'Làm giàu nhờ thu lợi nhuận từ các nước thuộc địa.', true),
(212, 53,'Áp dụng thành tựu khoa học – kĩ thuật.', false),
(213, 54,'Những năm 60 của thế kỉ XX.', true),
(214, 54,'Những năm 70 của thế kỉ XX.', false),
(215, 54,'Những năm 80 của thế kỉ XX.', false),
(216, 54,'Những năm 90 của thế kỉ XX.', false),
(217, 55,'Tây Âu, Nhật Bản vươn lên mạnh mẽ trở thành những trung tâm kinh tế cạnh tranh gay gắt với Mĩ.', false),
(218, 55,'Nền kinh tế Mĩ không ổn định, vấp phải suy thoái, khủng hoảng.', false),
(219, 55,'Mĩ chi khoản tiền lớn cho việc chạy đua vũ trang và các cuộc chiến tranh xâm lược.', false),
(220, 55,'Ở Mĩ liên tục xảy ra các cuộc nội chiến.', true),
(221, 56,'Anh', false),
(222, 56,'Pháp', false),
(223, 56,'Mĩ.', true),
(224, 56,'Nhật', false),
(225, 57,'Đưa con người lên mặt trăng.', true),
(226, 57,'Sản xuất tàu vũ trụ.', false),
(227, 57,'Sản xuất tàu con thoi.', false),
(228, 57,'Phóng thành công vệ tinh nhân tạo.', false),
(229, 58,'Đảng Dân chủ và Đảng Độc lập.', false),
(230, 58,'Đảng Dân chủ và Đảng Cộng hòa.', true),
(231, 58,'Đảng Cộng hòa và Đảng Độc lập.', false),
(232, 58,'Đảng Tự do và Đảng Cộng hòa.', false),
(233, 59,'Đưa Mĩ trở thành cường quốc về chính trị.', false),
(234, 59,'Đưa Mĩ trở thành cường quốc về kinh tế, tài chính.', false),
(235, 59,'Thực hiện mưu đồ làm bá chủ thế giới.', true),
(236, 59,'Mở rộng quan hệ ngoại giao với tất cả các nước trên thế giới.', false),
(237, 60,'Chống phá các nước xã hội chủ nghĩa.', false),
(238, 60,'Mở rộng quan hệ ngoại giao với tất cả các nước trên thế giới.', true),
(239, 60,'Đẩy lùi phong trào giải phóng dân tộc.', false),
(240, 60,'Thiết lập sự thống trị trên toàn thế giới.', false),
(241, 61,'Cải cách ruộng đất.', false),
(242, 61,'Ban hành hiên pháp 1946.', false),
(243, 61,'Chiến tranh Triều Tiên.', true),
(244, 61,'Chiến tranh Việt Nam.', false),
(245, 62,'Những cải cách dân chủ.', false),
(246, 62,'Ban hành hiến pháp năm 1946.', false),
(247, 62,'Chiến tranh Triều Tiên.', false),
(248, 62,'Chiến tranh Việt Nam.', true),
(249, 63,'Vươn lên đứng đầu trong giới tư bản chủ nghĩa.', false),
(250, 63,'Đứng thứ hai trong giới tư bản chủ nghĩa.', true),
(251, 63,'Đứng thứ ba trong giới tư bản chủ nghĩa.', false),
(252, 63,'Đứng thứ tư trong giới tư bản chủ nghĩa.', false),
(253, 64,'Những năm 60 của thế kỉ XX.', false),
(254, 64,'Những năm 70 của thế kỉ XX.', true),
(255, 64,'Những năm 80 của thế kỉ XX.', false),
(256, 64,'Những năm 90 của thế kỉ XX.', false),
(257, 65,'Yếu tố con người.', true),
(258, 65,'Vai trò của nhà nước trong điều tiết nền kinh tế.', false),
(259, 65,'Việc áp dụng những thành tựu khoa học – kĩ thuật.', false),
(260, 65,'Các công ti Nhật Bản có sức cạnh tranh cao.', false),
(261, 66,'Sau năm 1973.', false),
(262, 66,'Đầu những năm 80 của thế kỉ XX.', false),
(263, 66,'Cuối những năm 80 của thế kỉ XX.', false),
(264, 66,'Đầu những năm 90 của thế kỉ XX.', true),
(265, 67,'Coi trọng nền giáo dục quốc dân, khoa học – kĩ thuật.', false),
(266, 67,'Mua bằng phát minh, sáng chế của nước ngoài.', true),
(267, 67,'Cho người đi học tập ở nước ngoài.', false),
(268, 67,'Mời những người giỏi về làm việc.', false),
(269, 68,'Đảng Cộng sản Nhật Bản.', false),
(270, 68,'Đảng Dân chủ Xã hội.', false),
(271, 68,'Đảng Dân chủ Tự do.', true),
(272, 68,'Đảng Komeito.', false),
(273, 69,'Nhật Bản muốn lợi dụng vốn kĩ thuật của Mĩ để phát triển kinh tế.', false),
(274, 69,'Nhật Bản đặt dưới “ô bảo hộ hạt nhân” của Mĩ để giảm chi phí quân sự.', true),
(275, 69,'Tạo thế cân bằng giữa Mĩ và Nhật.', false),
(276, 69,'Mĩ giúp Nhật trở thành bá chủ châu Á.', false),
(277, 70,'Vươn lên trở thành cường quốc chính trị.', true),
(278, 70,'Duy trì vị thế siêu cường kinh tế.', false),
(279, 70,'Vươn lên trở thành nền kinh tế lớn nhất thế giới.', false),
(280, 70,'Giữ mối quan hệ ngoại giao tốt đẹp với tất cả các nước trên thế giới.', false),
(281, 71,'Tăng tỉ trọng của ngành chăn nuôi, giảm tỉ trọng ngành trồng trọt.', true),
(282, 71,'Tăng tỉ trọng cây cây lương thực, giảm tỉ trọng cây công nghiệp.', false),
(283, 71,'Tăng tỉ trọng cây công nghiệp hàng năm, giảm tỉ trọng cây công nghiệp lâu năm.', false),
(284, 71,'Tăng tỉ trọng cây lúa, giảm tỉ trọng cây hoa màu.', false),
(285, 72,'Cây lương thực', true),
(286, 72,'Cây hoa màu', false),
(287, 72,'Cây công nghiệp', false),
(288, 72,'Cây ăn quả và rau đậu', false),
(289, 73,'Độc canh cây hoa màu sang đa dạng cơ cấu cây công nghiệp, cây trồng khác.', false),
(290, 73,'Độc canh cây lương thực sang đa dạng cơ cấu cây công nghiệp, cây trồng khác.', false),
(291, 73,'Độc canh cây công nghiệp sang đa dạng cơ cấu cây lương thực và cây trồng.', false),
(292, 73,'Độc canh cây lúa sang đa dạng cơ cấu cây công nghiệp, cây trồng khác.', true),
(293, 74,'Đồng bằng sông Hồng và Đồng bằng sông Cửu long.', true),
(294, 74,'Các đồng bằng ven biển Duyên hải Nam Trung Bộ.', false),
(295, 74,'Trung du miền núi phía Bắc, Tây Nguyên.', false),
(296, 74,'Đồng bằng sông Hồng, Đông Nam Bộ.', false),
(297, 75,'Lúa được trồng rộng rãi trên khắp cả nước.', false),
(298, 75,'Cơ cấu mùa vụ đã thay đổi nhiều.', true),
(299, 75,'Đã hình thành được hai vùng trọng điểm lúa.', false),
(300, 75,'Cơ cấu ngành tròng trọt ngày càng đa dạng.', false),
(301, 76,'Diện tích đất trồng bị thu hẹp.', false),
(302, 76,'Công nghiệp chế biến trở thành ngành trọng điểm.', false),
(303, 76,'Đã đảm bảo được lương thực thực phẩm.', true),
(304, 76,'Diện tích rừng nước ta bị thu hẹp.', false),
(305, 77,'Bắc Trung Bộ và Đồng bằng sông Cửu long.', false),
(306, 77,'Trung du miền núi phía Bắc, Đông Nam Bộ.', false),
(307, 77,'Trung du miền núi phía Bắc, Bắc Trung Bộ.', true),
(308, 77,'Đồng bằng sông Hồng, Bắc Trung Bộ.', false),
(309, 78,'Nước ta đất hẹp người đông nên chăn nuôi khó phát triển.', false),
(310, 78,'Ít có nhiều đồng cỏ rộng, nguồn thức ăn còn thiếu.', true),
(311, 78,'Giống gia súc, gia cầm có chất lượng thấp.', false),
(312, 78,'Cơ sở vật chất cho chăn nuôi đã được cải thiện nhiều.', false),
(313, 79,'Các đồng cỏ tươi tốt', false),
(314, 79,'Vùng trồng cây ăn quả', false),
(315, 79,'Vùng trồng cây công nghiệp', false),
(316, 79,'Vùng trồng cây lương thực', true),
(317, 80,'Nông nghiệp đang được da dạng hóa.', true),
(318, 80,'Nước ta đang thoát khỏi tình trạng độc canh cây lúa nước.', false),
(319, 80,'Nông nghiệp không còn giữ vai trò quan trọng trong kinh tế.', false),
(320, 80,'Cơ cấu bữa ăn đã thay đổi theo hướng tăng thực phẩm, giẳm lương thực.', false),
(321, 81,'Địa hình', false),
(322, 81,'Khí hậu', false),
(323, 81,'Vị trí địa lý', false),
(324, 81,'Khoáng sản', true),
(325, 82,'Đàn trâu.', false),
(326, 82,'Đàn lợn.', false),
(327, 82,'Đàn bò.', false),
(328, 82,'Đàn gà, vịt.', true),
(329, 83,'Mangan, Crôm', false),
(330, 83,'Than đá, dầu khí', true),
(331, 83,'Apatit, pirit', false),
(332, 83,'Crôm, pirit', false),
(333, 84,'Công nghiệp năng lượng', false),
(334, 84,'Công nghiệp luyện kim màu', false),
(335, 84,'Công nghiệp hóa chất', true),
(336, 84,'Công nghiệp vật liệu xây dựng', false),
(337, 85,'Than', false),
(338, 85,'Hoá dầu', false),
(339, 85,'Nhiệt điện', true),
(340, 85,'Thuỷ điện', false),
(341, 86,'Công nghiệp luyện kim đen', false),
(342, 86,'Công nghiệp luyện kim màu', false),
(343, 86,'Công nghiệp năng lượng, hóa chất', true),
(344, 86,'Công nghiệp vật liệu xây dựng', false),
(345, 87,'Công nghiệp chế biến thực phẩm', false),
(346, 87,'Công nghiệp luyện kim màu', true),
(347, 87,'Công nghiệp năng lượng, hóa chất', false),
(348, 87,'Công nghiệp vật liệu xây dựng', false),
(349, 88,'Dân cư và lao động.', false),
(350, 88,'Thị trường, chính sách phát triển công nghiệp', true),
(351, 88,'Các nhân tố kinh tế - xã hội.', false),
(352, 88,'Cơ sở vật chất kĩ thuật trong công nghiệp và cơ sở hạ tầng', false),
(353, 89,'Công nghiệp dầu khí.', false),
(354, 89,'Công nghiệp sản xuất hàng tiêu dùng.', true),
(355, 89,'Công nghiệp cơ khí và hoá chất.', false),
(356, 89,'Công nghiệp điện tử.', false),
(357, 90,'Nguồn lao động', false),
(358, 90,'Cơ sở hạ tầng', false),
(359, 90,'Chính sách, thị trường', false),
(360, 90,'Nguồn tài nguyên khoáng sản', true),
(361, 91,'Bắc Phi', true),
(362, 91,'Trung Phi', false),
(363, 91,'Nam Phi', false),
(364, 91,'Đông Phi', false),
(365, 92,'An-giê-ri', false),
(366, 92,'Ai Cập', true),
(367, 92,'Nam Phi', false),
(368, 92,'Xu-đăng', false),
(369, 93,'Cuộc binh biến của sĩ quan Ai Cập', true),
(370, 93,'Cuộc nổi dậy của nhân dân Libi', false),
(371, 93,'Cuộc đấu tranh của Angiêri', false),
(372, 93,'“Năm châu Phi”', false),
(373, 94,'Phát xít Nhật', false),
(374, 94,'Phát xít Italia', false),
(375, 94,'Thực dân Tây Ban Nha', false),
(376, 94,'Thực dân Bồ Đào Nha', true),
(377, 95,'Angiêri giành được độc lâp', false),
(378, 95,'“Năm châu Phi”', true),
(379, 95,'Môdămbích, Ănggôla giành được độc lập', false),
(380, 95,'Tổ chức thống nhất châu Phi được thành lập', false),
(381, 96,'Có 17 nước ở Châu Phi được trao trả độc lập.', true),
(382, 96,'Phong trào giải phóng dân tộc phát triển mạnh nhất.', false),
(383, 96,'Tất cả các nước ở Châu Phi được trao trả độc lập.', false),
(384, 96,'Châu Phi là lục địa mới trỗi dậy.', false),
(385, 97,'Angiêri giành được độc lâp (1962)', false),
(386, 97,'“Năm châu Phi” (1960)', false),
(387, 97,'Môdămbích, Ănggôla giành được độc lập (1975)', true),
(388, 97,'Nam Rôđêdia giành được độc lập (1980)', false),
(389, 98,'Năm 1952 nhân dân Ai Cập lật đổ vương triều Pharúc.', false),
(390, 98,'Năm 1960 có 17 nước được trao trả độc lập (Năm châu Phi).', false),
(391, 98,'Năm 1975 với thắng lợi của nhân dân Môdămbích và Ănggôla.', true),
(392, 98,'Năm 1990 Cộng hòa Namibia tuyên bố độc lập.', false),
(393, 99,'Cơ bản chấm dứt sự tồn tại của chủ nghĩa thực dân cũ ở châu Phi.', true),
(394, 99,'Nenxon Manđêla trở thành tổng thống da đen đầu tiên.', false),
(395, 99,'Chính thức xóa bỏ chế độ phân biệt chủng tộc Apacthai.', false),
(396, 99,'Có 17 quốc gia lần lượt tuyên bố độc lập.', false),
(397, 100,'J. Nêru', false),
(398, 100,'M. Gandi', false),
(399, 100,'Phiđen cátxtơrô', false),
(400, 100,'Nenxơn Manđêla', true),
(401, 101,'Sự chấm dứt chủ nghĩa phân biệt chủng tộc ở châu Phi kéo dài ba thế kỉ', true),
(402, 101,'Đánh dấu sự bình đẳng của các dân tộc, màu da trên thế giới', false),
(403, 101,'Sự sụp đổ hoàn toàn của chủ nghĩa thực dân trên toàn thế giới', false),
(404, 101,'Sự thắng lợi của phong trào giải phóng dân tộc ở châu Phi', false),
(405, 102,'Hình thức chủ nghĩa thực dân kiểu mới bắt đầu vào khủng hoảng, suy yếu.', false),
(406, 102,'Một biện pháp thống trị của chủ nghĩa thực dân bị xóa bỏ.', true),
(407, 102,'Hệ thống thuộc địa của chủ nghĩa thực dân kiểu cũ bị tan rã hoàn toàn.', false),
(408, 102,'Cuộc đấu tranh vì tiến bộ xã hội đã hoàn thành ở châu Phi.', false),
(409, 103,'Sự thắng lợi của phong trào giải phóng dân tộc trên thế giới.', false),
(410, 103,'Đánh dấu sự bình đẳng của các dân tộc, màu da trên thế giới.', false),
(411, 103,'Sự sụp đổ hoàn toàn của chủ nghĩa thực dân trên thế giới.', false),
(412, 103,'Sự xóa bỏ hoàn toàn của chủ nghĩa phân biệt chủng tộc ở Nam Phi.', true),
(413, 104,'chế độ phong kiến.', false),
(414, 104,'chế độ nô lệ.', false),
(415, 104,'chủ nghĩa thực dân kiểu mới.', false),
(416, 104,'chủ nghĩa thực dân kiểu cũ.', true),
(417, 105,'Chiến tranh cách mạng.', false),
(418, 105,'Khởi nghĩa vũ trang.', false),
(419, 105,'Đấu tranh nghị trường.', false),
(420, 105,'Chính trị- ngoại giao.', true),
(421, 106,'Lãnh tụ của phong trào đấu tranh chống chế độ phân biệt chủng tộc ở Nam Phi', true),
(422, 106,'Chiến sĩ nổi tiếng chống ách thống trị của thực dân phương Tây', false),
(423, 106,'Lãnh tụ của phong trào giải phóng dân tộc ở An-giê-ri', false),
(424, 106,'Lãnh tụ của phong trào giải phóng dân tộc ở Ăng-gô-la', false),
(425, 107,'Hiến pháp tháng 11-1993', true),
(426, 107,'Hiến pháp tháng 10-1993', false),
(427, 107,'Hiến pháp tháng 12-1993', false),
(428, 107,'Hiến pháp tháng 4-1994', false),
(429, 108,'Chính thức xóa bỏ chế độ phân biệt chủng tộc Apacthai.', true),
(430, 108,'Xóa bỏ hệ thống chính quyền cai trị của người da trắng.', false),
(431, 108,'Đưa Nenxon Mađêla trở thành tổng thống da đen đầu tiên.', false),
(432, 108,'Lật đổ ách cai trị trong nhiều thế kỷ của thực dân Anh.', false),
(433, 109,'Sự thất bại của chủ nghĩa phát xít', false),
(434, 109,'Sự suy yếu của thực dân Anh, Pháp', false),
(435, 109,'Sự thắng lợi của phong trào giải phóng dân tộc ở Việt Nam, Trung Quốc', false),
(436, 109,'Sự phát triển về ý thức dân tộc của các quốc gia ở châu Phi', true),
(437, 110,'Chế độ phân biệt chủng tộc ở Nam Phi là không phù hợp với ý Chúa', false),
(438, 110,'Nam Phi chưa giành được độc lập dân tộc', false),
(439, 110,'Chế độ phân biệt chủng tộc là một hình thái áp bức của chủ nghĩa thực dân.', true),
(440, 110,'Chế độ phân biệt chủng tộc không được Hiến pháp Nam Phi thừa nhận', false),
(441, 111,'Đồng bằng', false),
(442, 111,'Đồi núi thấp', true),
(443, 111,'Núi trung bình', false),
(444, 111,'Núi cao', false),
(445, 112,'sự xâm thực mạnh mẽ tại miền đồi núi và bồi lắng phù sa tại các vùng trũng.', true),
(446, 112,'sự đa dạng của địa hình: đồi núi, cao nguyên, đồng bằng…', false),
(447, 112,'sự phân hóa rõ theo độ cao với nhiều bậc địa hình', false),
(448, 112,'cấu trúc địa hình gồm 2 hướng chính: tây bắc – đông nam và vòng cung', false),
(449, 113,'Địa hình của vùng nhiệt đới ẩm gió mùa.', true),
(450, 113,'Địa hình đồi núi chiếm phần lớn diện tích nhưng chủ yếu là đồi núi thấp.', false),
(451, 113,'Địa hình nước ta khá đa dạng', false),
(452, 113,'Địa hình chịu tác động mạnh mẽ của con người.', false),
(453, 114,'Đông Bắc, Đông Nam, Tây Bắc, Tây Nam.', false),
(454, 114,'Hoàng Liên Sơn, Trường Sơn Bắc, Trường Sơn Nam, Tây Bắc', false),
(455, 114,'Đông Bắc, Tây Bắc, Trường Sơn Bắc, Trường Sơn Nam.', true),
(456, 114,'Hoàng Liên Sơn, Tây Bắc, Đông Bắc, Trường Sơn.', false),
(457, 115,'dãy Hoàng Liên Sơn', false),
(458, 115,'dãy Hoành Sơn', true),
(459, 115,'sông Cả', false),
(460, 115,'dãy Bạch Mã', true),
(461, 116,'Gồm các khối núi và cao nguyên', false),
(462, 116,'Có nhiều dãy núi cao và đồ sộ nhất nước ta.', false),
(463, 116,'Có bốn cánh cung ', false),
(464, 116,'Địa hình thấp và hẹp ngang.', true),
(465, 117,'Thừa Thiên Huế và Đà Nẵng.', false),
(466, 117,'Hà Tĩnh và Quảng Bình.', false),
(467, 117,'Quảng Trị và Quảng Bình.', false),
(468, 117,'Thanh Hóa và Nghệ An', false),
(469, 118,'Có các cánh cung lớn mở ra về phía Bắc và Đông', true),
(470, 118,'Địa hình cao nhất nước ta với các dãy núi lớn, hướng Tây bắc – Đông Nam', false),
(471, 118,'Gồm các dãy núi song song và so le theo hướng Tây bắc – Đông nam', true),
(472, 118,'Gồm các khối núi và các cao nguyên xếp tầng đất đỏ badan.', false),
(473, 119,'Rìa phía Đông của bán đảo Đông Dương', false),
(474, 119,'Rìa phía Tây của bán đảo Đông Dương.', false),
(475, 119,'Trung tâm châu Á', false),
(476, 119,'Phía đông Đông Nam Á', false),
(477, 120,'Có các cánh cung lớn mở ra về phía Bắc và Đông', false),
(478, 120,'Địa hình cao nhất nước ta với các dãy núi lớn, hướng Tây bắc – Đông Nam', true),
(479, 120,'Gồm các dãy núi song song và so le theo hướng Tây bắc – Đông nam', false),
(480, 120,'Gồm các khối núi và các cao nguyên xếp tầng đất đỏ badan.', false),
(481, 121,'Địa hình đồi núi thấp chiếm phần lớn diện tích lãnh thổ.', true),
(482, 121,'Có 4 cánh cung lớn chụm lại ở Tam Đảo.', false),
(483, 121,'Gồm các dãy núi song song và so le hướng Tây Bắc – Đông Nam.', false),
(484, 121,'Giáp biên giới Việt - Trung là các khối núi đá vôi đồ sộ.', true),
(485, 122,'Trường Sơn Bắc có địa hình núi cao hơn Trường Sơn Nam', false),
(486, 122,'Trường sơn Bắc chủ yếu là núi thấp, trung bình; Trường Sơn Nam gồm khối núi cao đồ sộ.', false),
(487, 122,'Trường Sơn Bắc địa hình núi dưới 2000m, Trường Sơn Nam có đỉnh núi cao nhất trên 3000m', false),
(488, 122,'Trường Sơn Nam có núi cao hơn Trường Sơn Bắc và cao nhất cả nước', false),
(489, 123,'Hẹp ngang.', false),
(490, 123,'Bị chia cắt thành nhiều đồng bằng nhỏ.', true),
(491, 123,'Chỉ có một số đồng bằng được mở rộng ở các cửa sông lớn.', false),
(492, 123,'Được hình thành chủ yếu do các sông bồi đắp.', true),
(493, 124,'Bề mặt bị chia cắt thành nhiều ô.', false),
(494, 124,'Bị chia cắt thành nhiều đồng bằng nhỏ.', false),
(495, 124,'Có các khu ruộng cao bạc màu.', false),
(496, 124,'Được hình thành do phù sa sông bồi đắp.', true),
(497, 125,'Sông Mã – Chu.', false),
(498, 125,'Sông Cả.', false),
(499, 125,'Sông Gianh.', false),
(500, 125,'Sông Thu Bồn.', true),
(501, 126,'Vùng trung tâm có các dãy núi thấp với độ cao trung bình.', false),
(502, 126,'Nghiêng theo hướng tây bắc – đông nam', false),
(503, 126,'Có nhiều sơn nguyên, cao nguyên đá vôi.', true),
(504, 126,'Có nhiều khối núi cao, đồ sộ.', false),
(505, 127,'Hướng tây bắc - đông nam và hướng vòng cung.', false),
(506, 127,'Hướng tây nam - đông bắc và hướng vòng cung.', false),
(507, 127,'Hướng bắc - nam và hướng vòng cung.', false),
(508, 127,'Hướng đông - tây và hướng vòng cung.', true),
(509, 128,'Diện tích rộng hơn Đồng bằng sông Cửu Long', false),
(510, 128,'Hệ thống đê điều chia đồng bằng thành nhiều ô', false),
(511, 128,'Hệ thống kênh rạch chằng chịt.', false),
(512, 128,'Thủy triều xâm nhập gần như sâu toàn bộ đồng bằng về mùa cạn.', false),
(513, 129,'Diện tích nhỏ hơn Đồng bằng sông Hồng.', true),
(514, 129,'Hệ thống đê điều chia đồng bằng thành nhiều ô.', false),
(515, 129,'Có hệ thống sông ngòi kênh rạch chằng chịt hơn.', false),
(516, 129,'Độ cao địa hình lớn hơn Đồng bằng sông Hồng.', false),
(517, 130,'Được hình thành do tác động của dòng chảy chia cắt các thềm phù sa cổ.', false),
(518, 130,'Có cả đất phù sa cổ lẫn đất badan.', false),
(519, 130,'Được nâng lên yếu trong vận động Tân kiến tạo.', false),
(520, 130,'Nằm chuyển tiếp giữa miền núi và đồng bằng.', true),
(521, 131,'Tiêu diệt tận gốc chủ nghĩa phát xít Đức và chủ nghĩa quân phiệt Nhật Bản', false),
(522, 131,'Hợp tác giữa các nước nhằm khôi phục lại đất nước sau chiến tranh', true),
(523, 131,'Thỏa thuận về việc đóng quân tại các nước nhằm giải pháp quân đội phát xít, phân chia phạm vi ảnh hưởng ở châu Âu và châu Á .', false),
(524, 131,'Thành lập tổ chức Liên hợp quốc nhằm duy trì hòa bình và an ninh thế giới', false),
(525, 132,'Hoàn thành trước thời hạn kế hoạch 5 năm khôi phục kinh tế (1946 – 1950)', true),
(526, 132,'Nghiên cứu và chế tạo thành công bom nguyên tử', false),
(527, 132,'Xây dựng hoàn chỉnh lí thuyết về mô hình XHCN', false),
(528, 132,'Giúp đỡ các nước Đông Âu hoàn thành xây dựng nhà nước dân chủ nhân dân', false),
(529, 133,'Không tham gia bất kì liên minh chính trị, quân sự nào', false),
(530, 133,'Không tham gia vào nhóm G7 và G8', false),
(531, 133,'Đều đẩy mạnh cải cách dân chủ, cải cách – mở cửa, hội nhập quốc tế', true),
(532, 133,'Không chi phí nhiều tiền của cho quốc phòng, an ninh', false),
(533, 134,'Trung Quốc gây xung đột biên giới với các nước láng giềng Liên Xô (1962) và Ấn Độ (1969)', false),
(534, 134,'Trung Quốc cải thiện mối quan hệ theo hướng hòa dịu với Mĩ', false),
(535, 134,'Trung Quốc thiết lập quan hệ ngoại giao(1950) và bình thường hóa quan hệ ngoại giao với Việt Nam (1991)', true),
(536, 134,'Trung Quốc bình thường hóa quan hệ với Liên Xô, Nhật Bản', false),
(537, 135,'1,4,3,2', false),
(538, 135,'2,4,3,1', false),
(539, 135,'2,1,4,3', true),
(540, 135,'1,4,2,4', false),
(541, 136,'Tôn trọng độc lập, chủ quyền và toàn vẹn lãnh thổ giữa các nước', false),
(542, 136,'Không can thiệp vào công việc nội bộ của nhau, không sử dụng vũ lực hoặc đe dọa bằng vũ lực đối với nhau', false),
(543, 136,'Chung sống hòa bình và mọi quyết định đều phải có sự nhất trí của 5 nước sáng lập', true),
(544, 136,'Giải quyết các tranh chấp bằng biện pháp hòa bình', false),
(545, 137,'Sở hữu ¾ dự trữ vàng của thế giới', false),
(546, 137,'Sản lượng công nghiệp chiếm hơn một nửa sản lượng công nghiệp toàn thế giới', false),
(547, 137,'Viện trợ cho các nước Tây Âu 17 tỉ đô la qua kế hoạch "phục hưng châu Âu"', true),
(548, 137,'Trở thành nước khởi đầu cuộc cách mạng khoa học – kĩ thuật hiện đại', false),
(549, 138,'Trở thành một trong ba trung tâm kinh tế - tài chính lớn nhất thế giới', true),
(550, 138,'Chi phối toàn bộ thế giới về chính trị và kinh tế', false),
(551, 138,'Cùng với Liên Xô phóng nhiều vệ tinh nhân tạo lên quỹ đạo Trái Đất', false),
(552, 138,'Ngăn chặn được sự ảnh hưởng của CNXH lan ra toàn thế giới', false),
(553, 139,'Di chứng từ cuộc chiến tranh xâm lược Việt Nam', true),
(554, 139,'Sự sa lầy của quân đội Mĩ trên chiến trường Ỉac', false),
(555, 139,'Vụ khủng bố ngày 11 – 9 – 2001 tại Trung tâm thương mại Mĩ', false),
(556, 139,'Tổng thống Mĩ – Kennodi bị ám sát', false),
(557, 140,'Từng là đồng minh trong chiến tranh chuyển sang đối đầu và đi tới tình trạng chiến tranh lạnh', true),
(558, 140,'Chuyển từ đối đầu sang đối thoại', false),
(559, 140,'Hợp tác với nhau trong việc giải quyết nhiều vấn đề quốc tế lớn', false),
(560, 140,'Mâu thuẫn gay gắt về quyền lợi', false),
(561, 141,'Diễn ra đầu tiên ở ngành chế tạo công cụ lao động', false),
(562, 141,'Diễn ra trên tất cả các lĩnh vực', false),
(563, 141,'Diễn ra với quy mô và tốc độ lớn chưa từng thấy', false),
(564, 141,'Khoa học trở thành lực lượng sản xuất trực tiếp', true),
(565, 142,'Ứng dụng các thành tựu khoa học – kĩ thuật vào sản xuất', false),
(566, 142,'Nâng cao trình độ tập trung vốn và lao động', false),
(567, 142,'Có được thị trường lớn để tăng cường xuất khẩu hàng hóa', false),
(568, 142,'Hợp tác kinh tế, thu hút vốn đầu tư và ứng dụng khoa học – kĩ thuật', true),
(569, 143,'Thắng lợi của Cách mạng tháng Mười Nga năm 1917 đã ảnh hưởng đến tư tưởng cứu nước của Người', false),
(570, 143,'Nguyễn Ái Quốc gửi bản Yêu Sách đến Hội nghị Vecxai(1919)', false),
(571, 143,'Đọc Sơ thảo lần thứ nhất những luận cương về vấn đề dân tộc và vấn đề thuộc địa của Lênin (7-1920)', true),
(572, 143,'Tán thành gia nhập Quốc tế Cộng sản và tham gia sáng lập Đảng Cộng sản Pháp (12 – 1920)', false),
(573, 144,'Tìm ra con đường cứu nước đúng đắn cho cách mạng Việt Nam', true),
(574, 144,'Truyền bá chủ nghĩa Mác – Lenin vào trong nước', false),
(575, 144,'Liên kết chặt chẽ cách mạng vô sản với cách mạng giải phóng dân tộc', false),
(576, 144,'Thành lập Hội Việt Nam Cách mạng Thanh niên', false),
(577, 145,'Quốc tế này bênh vực cho quyền lợi của các nước thuộc địa', true),
(578, 145,'Quốc tế này giúp nhân dân ta đấu tranh chống pháp', false),
(579, 145,'Quốc tế này đề ra đường lối cho cách mạng Việt Nam', false),
(580, 145,'Quốc tế này chủ trương thành lập Đảng cộng sản ở thuộc địa', false),
(581, 146,'An Nam Cộng sản đảng', false),
(582, 146,'Hội Việt Nam Cách mạng Thanh niên', true),
(583, 146,'Đông Dương cộng sản liên đoàn', false),
(584, 146,'Đông Dương Cộng sản đảng', false),
(585, 147,'Bắc Kì là nơi phong trào dân tộc dân chủ theo khuynh hướng vô sản phát triển mạnh, hội viên ở Bắc Kì nhạy bén về chính trị', true),
(586, 147,'Năm 1929, phong trào dân tộc dân chủ ở nước ta phát triển mạnh', false),
(587, 147,'Đáp ứng yêu cầu thành lập tổ chúc lãnh đạo cách mạng Việt Nam', false),
(588, 147,'Sự phân hóa của Hội Việt Nam Cách mạng Thanh niên', false),
(589, 148,'Chính cương vắn tắt, Sách lược vắn tắt của Đảng', true),
(590, 148,'Luận cương chính trị của Đảng', false),
(591, 148,'Chính cương, Sách lược của Đảng', false),
(592, 148,'Tuyên ngôn, Điều lệ của Đảng', false),
(593, 149,'Là người chủ trì Hội nghị', false),
(594, 149,'Thống nhất các tổ chức cộng sản để thành lập Đảng Cộng Sản Việt Nam', false),
(595, 149,'Soạn thảo Cương lĩnh chính trị đầu tiên của Đảng', false),
(596, 149,'Tuyên truyền chủ nghĩa Mác - Lênin cho những người Cộng sản Việt Nam', true),
(597, 150,'Chính cương vắn tắt, sách lược vắn tắt được thông qua tại Hội nghị thành lập Đảng Cộng Sản Việt Nam đầu năm 1930', false),
(598, 150,'Luận cương chính trị tháng 10-1930 của Đảng Cộng Sản Đông Dương', true),
(599, 150,'Nghị quyết chính trị, Điều lệ Đảng được thông qua tại Đại hội đại biểu lần thứ I Đảng Cộng Sản Đông Dương ( 3-1935)', false),
(600, 150,'Nghị quyết Hội nghị Ban Chấp hành Trung ương Đảng tháng 11-1939', false),
(601, 151,'nhiệt độ trung bình cao.', false),
(602, 151,'Độ ẩm không khí lớn.', true),
(603, 151,'Địa hình nhiều đồi núi.', false),
(604, 151,'Sự phân mùa khí hậu.', false),
(605, 152,'Cận xích đạo gió mùa.', false), 
(606, 152,'Ôn đới gió mùa.', false),
(607, 152,'Nhiệt đới gió mùa.', true),        
(608, 152,'Cận nhiệt đới gió mùa.', false),
(609, 153,'Hệ sinh thái trên đất phèn', false),
(610, 153,'Hệ sinh thái trên các đảo', false),
(611, 153,'Hệ sinh thái rừng ngập mặn', false),
(612, 153,'Hệ sinh thái rừng nửa rụng lá', true),
(613, 154,'Cát bay, cát chảy.', false),
(614, 154,'Động đất.', true),
(615, 154,'Sạt lở bò biển.', false),
(616, 154,'Bão.', false),
(617, 155,'Làm giảm tính chất lạnh khô vào mùa đông và dịu bớt thời tiết nóng bức vào mùa hè.', false),
(618, 155,'Mang lại lượng mưa và độ ẩm lớn.', false),
(619, 155,'Làm tăng tính chất nóng và khô của khí hậu nước ta.', true),
(620, 155,'Làm tăng độ ẩm của các khối khí qua biển.', false),
(621, 156,'Mang lại cho nước ta nhiệt độ cao, nóng quanh năm.', false),
(622, 156,'Mang lại cho nước ta một lượng mưa và độ ẩm lớn.', true),
(623, 156,'Mang lại cho nước ta các loại gió hoạt động theo mùa.', false),
(624, 156,'Mang lại tài nguyên sinh vật phong phú.', false),
(625, 157,'Hiện tượng cát bay, cát chảy.', false),
(626, 157,'Sạt lở bờ biển.', false),
(627, 157,'Tài nguyên sinh vật biển suy thoái nghiêm trọng.', false),
(628, 157,'Bão kèm theo mưa lớn, sóng lừng.', true),
(629, 158,'Nước ta chịu tác động thường xuyên của Tín phong Bắc bán cầu.', false),
(630, 158,'Địa hình 85% là đồi núi thấp.', false),
(631, 158,'Khí hậu ảnh hưởng của biển Đông.', true),
(632, 158,'Nước ta nằm gần Xích đạo, mưa nhiều.', false),
(633, 159,'Nằm gần Xích đạo, mưa nhiều.', false),
(634, 159,'Địa hình 85% là đồi núi thấp.', false),
(635, 159,'Chịu tác động thường xuyên của gió mùa.', false),
(636, 159,'Tiếp giáp với Biển Đông.', true),
(637, 160,'Khí hậu hải dương', true),
(638, 160,'Khí hậu lục địa', false),
(639, 160,'Khí hậu lục địa nửa khô hạn', false),
(640, 160,'Khí hậu cận nhiệt Địa Trung Hải.', false),
(641, 161,'Năng suất sinh vật cao.', true),
(642, 161,'Ít loài quý hiếm.', false),
(643, 161,'Nhiều loài đang cạn kiệt.', false),
(644, 161,'Tập trung theo mùa.', false),
(645, 162,'Biển Đông làm tăng độ ẩm tương đối của không khí.', false),
(646, 162,'Biển Đông làm giảm độ lục địa của các vùng phía tây đât nước.', false),
(647, 162,'Biển Đông làm tăng độ lạnh của gió mùa đông bắc.', true),
(648, 162,'Biển Đông mang lại một lượng mưa lớn.', false),
(649, 163,'Sa khoáng, khí đốt.', false),
(650, 163,'Ti tan, dầu mỏ.', false),
(651, 163,'Dầu mỏ, khí đốt.', true),
(652, 163,'Vàng, dầu mỏ.', false),
(653, 164,'Vùng biển giàu tài nguyên.', false),
(654, 164,'Mang lại khí hậu nhiệt đới.', false),
(655, 164,'Mang lại độ ẩm lớn, làm cho khí hậu nước ta mang tính hải dương.', true),
(656, 164,'Tạo nên cảnh quan độc đáo cho địa hình bờ biển.', false),
(657, 165,'Các bờ biển mài mòn', false),
(658, 165,'Vịnh cửa sông', false),
(659, 165,'Các đảo ven bờ', false),
(660, 165,'Các vũng, vịnh nước sâu', true),
(661, 166,'Thái Bình Dương và Đại Tây Dương', false),
(662, 166,'Đại Tây Dương và Ấn Độ Dương', false),
(663, 166,'Thái Bình Dương và Ấn Độ Dương', true),
(664, 166,'Thái Bình Dương và Bắc Băng Dương', false),
(665, 167,'Sự phong phú đa dạng của tài nguyên sinh vật biển.', false),
(666, 167,'Giàu dầu mỏ và khí đốt.', true),
(667, 167,'Có các dòng biển thay đổi theo mùa.', false),
(668, 167,'Nhiệt độ nước biển quanh năm cao trên 200C.', false),
(669, 168,'Bắc Trung Bộ.', false),
(670, 168,'Bắc Bộ.', false),
(671, 168,'Nam Bộ.', true),
(672, 168,'Nam Trung Bộ.', false),
(673, 169,'Cát bay, cát chảy.', false),
(674, 169,'Bão.', true),
(675, 169,'Sạt lở bờ biển.', false),
(676, 169,'Sóng thần.', false),
(677, 170,'Hơn 100 loài tôm.', false),
(678, 170,'Trên 2000 loài cá.', false),
(679, 170,'Các rạn san hô.', true),
(680, 170,'Nhiều loài sinh vật phù du.', false);





























